### ISSUE TITLE
Crash on block registration

### ISSUE THREAD

**Issue by Efimero** [tmetcalfe89/JsonifyCraft-1.15#4]
https://github.com/tmetcalfe89/JsonifyCraft-1.15/blob/734a97a94abddbced3fe252873a35821cf7323bd/src/main/java/us/timinc/mcutil/MCRegistry.java#L51

Forge: 28.1.107
Minecraft: 1.14.4

This line makes the mod crash with a NoSuchFieldError.

Log: https://gist.github.com/Efimero/94deb28df50de4bfcfe902e0d0362974

**Comment by tmetcalfe89-zz** [comment]
Ah, yeah, that makes sense. I will have to make a 1.14-specific version after all.

**Comment by tmetcalfe89-zz** [comment]
Solved! JsonifyCraft-1.14-v1.0.0 is now live. Give the Twitch client a second to catch up, or grab it at the link on this release.
https://github.com/tmetcalfe89/JsonifyCraft-1.14/releases/tag/v1.0.0
