### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Nachtflame** [tmetcalfe89/JsonifyCraft-1.15#5]
With an empty **{minecraft}\gameobjects** folder, everything loads fine.  When I try to define item/blocks in a file in the folder, game crashes on startup.

latest.log from attempted game-start -
https://pastebin.com/aQa5GAsX

forge 28.1.107
JsonifyCraft 1.15-1.0.1
MC 1.14.4

**Comment by tmetcalfe89-zz** [comment]
Same issue as is in #4. Same solution coming shortly.
